export const industryTypes = [
	"Accounting / Auditing",
	"Advertising & Marketing",
	"Agriculture / Forestry / Fishing",
	"Analytics / KPO / Research",
	"Animation & VFX",
	"Architecture / Interior Design",
	"Auto Components",
	"Automobile",
	"Aviation",
	"Banking",
	"Beauty & Personal Care",
	"Beverage",
	"Biotechnology",
	"BPO / Call Centre",
	"Building Material",
	"Chemicals",
	"Clinical Research / Contract Research",
	"Consumer Electronics & Appliances",
	"Content Development / Language",
	"Courier / Logistics",
	"Defence & Aerospace",
	"Design",
	"E-Learning / EdTech",
	"Education / Training",
	"Electrical Equipment",
	"Electronic Components / Semiconductors",
	"Electronics Manufacturing",
	"Emerging Technologies",
	"Engineering & Construction",
	"Events / Live Entertainment",
	"Facility Management Services",
	"Fertilizers / Pesticides / Agro chemicals",
	"Film / Music / Entertainment",
	"Financial Services",
	"FinTech / Payments",
	"Fitness & Wellness",
	"FMCG",
	"Food Processing",
	"Furniture & Furnishing",
	"Gaming",
	"Gems & Jewellery",
	"Government / Public Administration",
	"Hardware & Networking",
	"Hotels & Restaurants",
	"Import & Export",
	"Industrial Automation",
	"Industrial Equipment / Machinery",
	"Insurance",
	"Internet",
	"Investment Banking / Venture Capital / Private Equity",
	"Iron & Steel",
	"IT Services & Consulting",
	"Law Enforcement / Security Services",
	"Leather",
	"Legal",
	"Management Consulting",
	"Medical Devices & Equipment",
	"Medical Services / Hospital",
	"Metals & Mining",
	"Miscellaneous",
	"NBFC",
	"NGO / Social Services / Industry Associations",
	"Oil & Gas",
	"Packaging & Containers",
	"Petrochemical / Plastics / Rubber",
	"Pharmaceutical & Life Sciences",
	"Ports & Shipping",
	"Power",
	"Printing & Publishing",
	"Pulp & Paper",
	"Railways",
	"Real Estate",
	"Recruitment / Staffing",
	"Retail",
	"Software Product",
	"Sports / Leisure & Recreation",
	"Telecom / ISP",
	"Textile & Apparel",
	"Travel & Tourism",
	"TV / Radio",
	"Urban Transport",
	"Water Treatment / Waste Management",
];
