export const jobRoles = [
    "Software Developer",
    "Data Scientist",
    "Web Developer",
    "UX/UI Designer",
    "Product Manager",
    "Marketing Specialist",
    "Human Resources Manager",
    "Financial Analyst",
    "Project Manager",
    "Sales Representative",
    "Customer Support Specialist",
    "Graphic Designer",
    "Network Administrator",
    "Systems Analyst",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Civil Engineer",
    "Medical Doctor",
    "Nurse Practitioner",
    "Pharmacist",
    "Teacher/Educator",
    "Research Scientist",
    "Journalist",
    "Chef",
    "Social Media Manager",
    "Digital Marketing Manager",
    "Cybersecurity Analyst",
    "Environmental Scientist",
    "Event Planner",
    "Fitness Trainer",
    "Translator/Interpreter",
    "Financial Advisor",
    "Real Estate Agent",
    "Electrician",
    "Plumber",
    "Mechanic",
    "Pilot",
    "Astronaut",
    "Fashion Designer",
    "Animator",
    "Film Director",
    "Biomedical Engineer",
    "Robotics Engineer",
    "Cryptocurrency Analyst",
    "Ethical Hacker",
    "Blockchain Developer",
    "Virtual Reality Developer",
    "Sustainability Consultant",
    "Genetic Counselor",
    "Wind Turbine Technician",
    "Solar Energy Technician",
    "Digital Health Specialist",
    "Telemedicine Doctor",
    "Remote Sensing Specialist",
    "SpaceX Launch Director",
    "Drone Pilot",
    "Esports Coach",
    "Bioinformatics Scientist",
    "Renewable Energy Engineer",
    "Quantum Computing Scientist",
    "Augmented Reality Developer",
    "Chief Happiness Officer",
]