const jobTags = [
    'html',
    'css',
    'web developer',
    'frontend',
    'javascript',
    'react',
    'angular',
    'vue.js',
    'responsive design',
    'UI/UX',
    'bootstrap',
    'jQuery',
    'web design',
    'web development',
    'full stack',
    'node.js',
    'express.js',
    'backend',
    'database',
    'SQL',
    'MongoDB',
    'RESTful API',
    'JSON',
    'AJAX',
    'PHP',
    'Laravel',
    'Symfony',
    'CodeIgniter',
    'Python',
    'Django',
    'Flask',
    'Ruby',
    'Ruby on Rails',
    'Java',
    'Spring',
    'Kotlin',
    'Android development',
    'iOS development',
    'Swift',
    'Objective-C',
    'mobile app development',
    'Xamarin',
    'Flutter',
    'Dart',
    'Git',
    'GitHub',
    'Bitbucket',
    'version control',
    'continuous integration',
    'Jenkins',
    'Docker',
    'Kubernetes',
    'cloud computing',
    'AWS',
    'Azure',
    'Google Cloud Platform',
    'DevOps',
    'Agile',
    'Scrum',
    'Kanban',
    'project management',
    'software engineering',
    'programming',
    'algorithms',
    'data structures',
    'cybersecurity',
    'network security',
    'penetration testing',
    'ethical hacking',
    'machine learning',
    'artificial intelligence',
    'data science',
    'big data',
    'Hadoop',
    'Spark',
    'natural language processing',
    'computer vision',
    'blockchain',
    'smart contracts',
    'Solidity',
    'cryptocurrency',
    'fintech',
    'e-commerce',
    'CMS (Content Management System)',
    'WordPress',
    'Joomla',
    'Drupal',
    'e-learning',
    'LMS (Learning Management System)',
    'SEO',
    'SEM',
    'digital marketing',
    'social media',
    'content writing',
    'blogging',
    'graphic design',
    'UI/UX design',
    'user research',
    'usability testing',
    'product management',
    'customer support',
    'technical support',
    'helpdesk',
    'IT consulting',
    'system administration',
    'network administration',
    'cloud architecture',
    'UI/UX prototyping',
    'wireframing',
    'user personas',
    'customer success',
    'sales',
    'business development',
    'account management',
    'market research',
    'data analysis',
    'business intelligence',
    'quality assurance',
    'software testing',
    'test automation',
    'QA engineering',
    'technical writing',
    'documentation',
    'system analysis',
    'UI/UX testing',
    'performance testing',
    'mobile testing',
    'game development',
    'virtual reality',
    'augmented reality',
    'UI/UX animation',
    'motion design'
  ];
  